config/routes.rb
Rails.application.routes.draw do
  resources :species do
    resources :sightings
  end
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :species

  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :sightings

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @species = Species.find(params[:species_id])
    @sighting = @species.sightings.new
  end

  def create
    @species = Species.find(params[:species_id])
    @sighting = @species.sightings.new(sighting_params)
    if @sighting.save
      redirect_to species_path(@species)
    else
      render :new
    end
  end

  private

  def sighting_params
    params.require(:sighting).permit(:latitude, :longitude, :region)
  end

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
  end

  def new
    @species = Species.new
  end

  def create
    @species = Species.new(species_params)
    if @species.save
      redirect_to species_path(@species)
    else
      render :new
    end
  end

  def show
    @species = Species.find(params[:id])
  end

  def edit
    @species = Species.find(params[:id])
  end

  def update
    @species = Species.find(params[:id])
    if @species.update(species_params)
      redirect_to species_path(@species)
    else
      render :edit
    end
  end

  def destroy
    @species = Species.find(params[:id])
    @species.destroy
    redirect_to species_index_path
  end

  private

  def species_params
    params.require(:species).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>:( Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wildlife</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= render "layouts/errors", object: @sighting %>

<%= form_for [@species, @sighting] do |f| %>
  <%= f.label :latitude %>
  <%= f.number_field :latitude, step: "any" %>

  <%= f.label :longitude %>
  <%= f.number_field :longitude, step: "any"  %>

  <%= f.submit %>
<% end %>

app/views/sightings/new.html.erb
<%= render "form" %>

app/views/species/_form.html.erb
<%= form_for @species do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/species/edit.html.erb
<%= render "layouts/errors", object: @species %>

<%= render "form" %>

app/views/species/index.html.erb
<h1>Current Species:</h1>

<% if @species.any? %>
  <ul>
    <% @species.each do |species| %>
      <li><%= link_to species.name, species_path(species) %></li>
    <% end %>
  </ul>
<% else %>
  <h3>Sorry, there are not any species yet.</h3>
<% end %>

<p>
  <%= link_to "Add a Species", new_species_path %>
</p>

app/views/species/new.html.erb
<%= render "layouts/errors", object: @species %>

<%= render "form" %>

app/views/species/show.html.erb
<h1><%= @species.name %></h1>

<% if @species.sightings.any? %>
  <ul>
    <% @species.sightings.each do |sighting| %>
      <li>
        <ul>
          <li><%= sighting.latitude %></li>
          <li><%= sighting.longitude %></li>
        </ul>
      </li>
    <% end %>
  </ul>
<% else %>
  <h3>There are no sightings for this species yet :(</h3>
<% end %>
<%= link_to "Add Sighting", new_species_sighting_path(@species) %>
<%= link_to "Back to Species", species_index_path %> |
<%= link_to "Edit", edit_species_path(@species) %> |
<%= link_to "Delete", species_path(@species), data: { confirm: "Are you sure?" }, method: :delete %>